### PR TITLE
Changed some animations in about.html

### PR DESCRIPTION
**Pull request by anthony10154**
just changed some animations so it doesn't look so "samey"

### CODE REVIEW

**Comment by dscatalan** [comment]
Can you wrap your animations in media queries. Things start to break on Mobile so I think it's best if we just target large screens for animations. It looks really good on desktop! 


Or you can try to fix the animations on mobile view instead of removing them! Up to you! 
Also try to use the clamp function for font-size instead of fixed pixel size. 

That way text will resize when viewing on smaller screens. 

Here is a live view of any changes you make to about-anim 

https://daysmachine.github.io/graduation-flow/gradflow.html

only **index.html** has issues. The other pages are fine as is

**Review by dscatalan — CHANGES_REQUESTED** [review]
Wrap animations in media queries to only display on larger screens. 

Or alternatively fix animations on mobile/Tablet view for index.html

**Comment by anthony10154** [comment]
alright, i believe animations will only play out now if screen is at least 1000px wide

**Comment by dscatalan** [comment]
Alright looks good thank you! I just added in the export change I made on main so you don't get any merge issues on that

**Review by dscatalan — APPROVED** [review]
looks good!

**Pull request merged**
