### PR TITLE
switch modify and view popup when clicking a node + small fixes to prep for iteration 5

### PR DESCRIPTION
**Pull request by dscatalan**

### CODE REVIEW

**Review by KosOrKosm — APPROVED** [review]
This works, but you might want to make the popup looks better when you click a mostly empty node. It looks kinda weird like the popup is mostly empty.

**Comment by dscatalan** [comment]
oh yeah good idea. maybe i can find a way to display a "No data Set" message or something. i couldn't figure out how to remove the prefix label if there is no input like i did the other labels btw. that is a bug.

**Comment by dscatalan** [comment]
see differences here: 
# [official graduation-flow](https://kosorkosm.github.io/graduation-flow/gradflow.html)
our official website on main 



# [my fork: graduation-flow](https://daysmachine.github.io/graduation-flow/gradflow.html)
Used to view branches before merging to official. currently on switchPopups

**Review by anthony10154 — APPROVED** [review]
ooooh  i like this a lot. It doesn't seem to break anything from what i can see.

**Pull request merged**
