### PR TITLE
added import from database popup

### PR DESCRIPTION
**Pull request by anthony10154**
a simple popup where there will be a dropdown menu that will "hopefully" dynamically add to the drop down menu

### CODE REVIEW

**Comment by dscatalan** [comment]
i'll let @KosOrKosm review this one since it needs to be implemented with database stuff

**Comment by KosOrKosm** [comment]
This isn't exactly how I was picturing it working. I was picturing a single search field, and a window in the middle to preview the nodes that would be displayed. You wouldn't have to render the nodes, just create a div for another p5 canvas to be placed in.

Currently, how is this import supposed to work? You can type in course information, but how can you know if there are any nodes that match to import? Would you just hit the button and hope it finds something? Seems very unfriendly for the user.

**Comment by KosOrKosm** [comment]
Separately, someone please fix the CSS on the description input field. I don't have a problem with adding it, but it looks really ugly currently. The whole popup menus could use a design revision since I would prefer they be centered on the screen and have a proper background. Something to consider.

**Comment by anthony10154** [comment]
ah this was more of a prototype, in case database/logic team needed to use a popup. Ill get to redesigning and centering the popups

**Comment by KosOrKosm** [comment]
Ah ok, thank you. It will be very useful to test the database integration. I'll need to check in with Alfredo on the progress of that

**Pull request closed without merging**
