### PR TITLE
unmerged viewNode branch 

### PR DESCRIPTION
**Pull request by dscatalan**

### CODE REVIEW

**Comment by dscatalan** [comment]
still work in progress but I have pushed what i have so far! Feel free to work on it if you want @anthony10154. Otherwise I will let you know when I next work on this so you can push any possible commits before I jump back in. 

Here are the trellos related to this 
https://trello.com/c/ixJplFaI
https://trello.com/c/tZ8Rlbcx

**Comment by dscatalan** [comment]
here is what I have so far

**Comment by KosOrKosm** [comment]
JS Portion looks good!

**Review by KosOrKosm — APPROVED** [review]

**Comment by dscatalan** [comment]
same as "edit css popups and add viewNode popup" PR. ignore this one.

**Pull request closed without merging**
